# Generated by Django 4.2.7 on 2025-10-18 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('encryption_password', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('monitoring_scope', models.CharField(default='all_users', max_length=50)),
                ('encryption_password', models.CharField(blank=True, max_length=255, null=True)),
                ('encryption_salt', models.CharField(default='default_salt_12345', max_length=255)),
                ('last_config_update', models.DateTimeField(auto_now=True)),
                ('config_version', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Channel', max_length=100)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('discord', 'Discord'), ('slack', 'Slack'), ('webhook', 'Webhook')], default='email', max_length=10)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Threshold', max_length=100)),
                ('resource_type', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'Memory'), ('disk', 'Disk'), ('network', 'Network'), ('process', 'Process')], default='cpu', max_length=10)),
                ('threshold_value', models.FloatField(default=80.0)),
                ('comparison', models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('=', 'Equal To')], default='>', max_length=5)),
                ('process_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processes', models.JSONField(default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.monitoringagent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('alert_type', models.CharField(choices=[('process', 'Process'), ('network', 'Network'), ('authentication', 'Authentication'), ('resource', 'Resource'), ('security', 'Security'), ('system', 'System')], default='system', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.monitoringagent')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('terminal', models.CharField(max_length=100)),
                ('host', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField()),
                ('pid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.monitoringagent')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'username'], name='monitoring__agent_i_813434_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.monitoringagent')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'timestamp'], name='monitoring__agent_i_a261e9_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_f9e144_idx')],
            },
        ),
        migrations.CreateModel(
            name='HostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('memory_total', models.BigIntegerField(default=0)),
                ('memory_used', models.BigIntegerField(default=0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('disk_total', models.BigIntegerField(default=0)),
                ('disk_used', models.BigIntegerField(default=0)),
                ('network_sent', models.BigIntegerField(default=0)),
                ('network_received', models.BigIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.monitoringagent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', 'timestamp'], name='monitoring__agent_i_dffda5_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_4ccc12_idx')],
            },
        ),
    ]
