# Generated by Django 4.2.7 on 2025-10-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationchannel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resourcethreshold',
            options={'ordering': ['name']},
        ),
    ]
