# Generated by Django 4.2.7 on 2025-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringagent',
            name='encryption_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitoringagent',
            name='encryption_salt',
            field=models.CharField(default='default_salt_12345', max_length=255),
        ),
    ]
