# Generated by Django 4.2.7 on 2025-10-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_notificationchannel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('process', 'Process'), ('network', 'Network'), ('authentication', 'Authentication'), ('resource', 'Resource'), ('security', 'Security'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
