# Generated by Django 4.2.7 on 2025-10-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alert_alert_type_alert_metadata_alert_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-triggered_at']},
        ),
    ]
