services:
  db:
    image: postgres:15
    container_name: monitoring_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=monitoring_db
      - POSTGRES_USER=monitoring_user
      - POSTGRES_PASSWORD=monitoring_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitoring_user -d monitoring_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
